### PR TITLE
Update ember-template-compiler to 1.11.0

### PR DESCRIPTION
**Pull request by dgaus**

### CODE REVIEW

**Comment by toranb** [comment]
Does this require ember ship w/ the template compiler as Robert suggested here?

https://github.com/toranb/ember-template-compiler/pull/30

**Comment by dgaus** [comment]
I'm just updating the ember-template-compiler.js file that's already in lib. It would probably be better to just use the one included in Ember, but I am not that familiar with NPM packaging

**Comment by toranb** [comment]
Understood - a more clear version of my question 

"if I update just the ember-template-compiler.js file will it work in the real world"?

As I'm not into django dev these days I didn't test this manually - if you pull down the latest django-ember-precompile and hack your node_modules (by hand) does everything just work?

Thanks for the help - sorry this project doesn't include a functional integration test suite to give me more confidence :)

**Comment by dgaus** [comment]
Sorry, we ended up switching to Ember-cli, so I won't get a chance to test properly. It should work as far as I know.

**Pull request closed without merging**
